# Common Data Structures

## Arrays


Array's are N-dimensional data structures of a common type (the type could be `Any`).  The type signature is

```julia
Array{T, N}
```

where `T` is the type and `N` is the dimension.  You can omit `N` and it will be inferred for the arguments

In [1]:
Array{Any, 3}(nothing, 3, 2, 3)

3×2×3 Array{Any, 3}:
[:, :, 1] =
 nothing  nothing
 nothing  nothing
 nothing  nothing

[:, :, 2] =
 nothing  nothing
 nothing  nothing
 nothing  nothing

[:, :, 3] =
 nothing  nothing
 nothing  nothing
 nothing  nothing

In [2]:
x = Array{Any}(nothing, 2, 3)

2×3 Matrix{Any}:
 nothing  nothing  nothing
 nothing  nothing  nothing

A `Vector` is an `Array` with `N=1`, a `Matrix` is an `Array` with `N=2`.

In [3]:
Vector{Float64}(undef, 3)

3-element Vector{Float64}:
 6.9411096333322e-310
 6.94110963341126e-310
 6.94110963333853e-310

In [4]:
Matrix{Float64}(undef, 3, 3)

3×3 Matrix{Float64}:
 6.4e-323  3.0e-323  1.0e-323
 3.5e-323  2.0e-323  5.0e-324
 2.5e-323  1.5e-323  6.89903e-310

In [5]:
Float64[1.0, 2.0, 3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [6]:
y = Float64[1.0 2.0 3.0; 4.0 5.0 6.0]

2×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0

## Array indexing and assignment

In [7]:
y[1, 2]

2.0

In [8]:
y[1:2, 2]

2-element Vector{Float64}:
 2.0
 5.0

In [9]:
y[end,end] = 100;
y

2×3 Matrix{Float64}:
 1.0  2.0    3.0
 4.0  5.0  100.0

In [10]:
x[1, 1] = "test"
x[2, 1:3] .= 1
x

2×3 Matrix{Any}:
  "test"   nothing   nothing
 1        1         1

## Views

In [11]:
z = y[1:2, 1:2]

2×2 Matrix{Float64}:
 1.0  2.0
 4.0  5.0

In [12]:
z[1,1] = 100.0
@show z
@show y;

z = [100.0 2.0; 4.0 5.0]
y = [1.0 2.0 3.0; 4.0 5.0 100.0]


In [13]:
z = @view y[1:2, 1:2]
z[1, 1] = 100.0
y

2×3 Matrix{Float64}:
 100.0  2.0    3.0
   4.0  5.0  100.0

## Convenience constructors

In [14]:
zeros(Int32, 2, 3)

2×3 Matrix{Int32}:
 0  0  0
 0  0  0

In [15]:
zeros(2, 3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [16]:
ones(2, 3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [17]:
fill(77.0, 2, 2)

2×2 Matrix{Float64}:
 77.0  77.0
 77.0  77.0

In [18]:
fill!(y, 22.0)

2×3 Matrix{Float64}:
 22.0  22.0  22.0
 22.0  22.0  22.0

## Operations on arrays

Multiplication of a `Matrix` and a `Vector` automatically does matrix multiplication.

In [19]:
@show y
@show x = [1.0, 2.0, 3.0]
y * x

y = [22.0 22.0 22.0; 22.0 22.0 22.0]
x = [1.0, 2.0, 3.0] = [1.0, 2.0, 3.0]


2-element Vector{Float64}:
 132.0
 132.0

If we want element-wise multiplication we need to use `.*`.

In [20]:
x .* x

3-element Vector{Float64}:
 1.0
 4.0
 9.0

Addition/subtraction of two `Array`s of the same size gives element-wise addition.

In [21]:
x + x

3-element Vector{Float64}:
 2.0
 4.0
 6.0

We can *broadcast* the addition operation along matching dimensions of `Array`s.

In [22]:
@show size(y')
@show size(x)

y' .+ x

size(y') = (3, 2)
size(x) = (3,)


3×2 Matrix{Float64}:
 23.0  23.0
 24.0  24.0
 25.0  25.0

Any scalar operation can be *vectorized* with the `.` operator, i.e.

In [23]:
my_scalar_operation(x, y) = x * y + x^2 * y^2

my_scalar_operation(1.0, 2.0)

6.0

In [24]:
my_scalar_operation.([1.0, 2.0, 3.0], [4.0, 5.0, 6.0])

3-element Vector{Float64}:
  20.0
 110.0
 342.0

## Array functions

There are numerous array functions such as `sum`, `cumsum`, `prod`, etc.  For example

In [25]:
accumulate(+, [1, 2, 3])

3-element Vector{Int64}:
 1
 3
 6

See [Array documentation](https://docs.julialang.org/en/v1.7/base/arrays/#Array-functions) for more examples.

## Tuples

Tuples are fixed length containers that can hold any values, but cannot be modified (they are *immutable*).

In [26]:
x = ("a string", 1.0, 33)

("a string", 1.0, 33)

In [27]:
x[1]

"a string"

In [28]:
x[2] = 2.0 

LoadError: MethodError: no method matching setindex!(::Tuple{String, Float64, Int64}, ::Float64, ::Int64)

## Named Tuples

In [29]:
x = (a = "a string", b = 1.0, c = 33) 

(a = "a string", b = 1.0, c = 33)

In [30]:
@show x[1]
@show x.a;

x[1] = "a string"
x.a = "a string"


In [31]:
_, bb, _ = x
@show bb;

bb = 1.0


## Dictionaries

Dictionaries are data structures to store and lookup key-value pairs, i.e.

In [32]:
dict = Dict("a" => "a string", "b" => 33, "name" => "John")

@show dict["b"]
@show dict["name"];

dict["b"] = 33
dict["name"] = "John"


They can also be constructed using a collection of tuples.

In [33]:
dict = Dict([("a","a string"), ("b", 33), ("name", "John")])

@show dict["b"]
@show dict["name"];

dict["b"] = 33
dict["name"] = "John"


## More Data Structures 

More information of these data structures as well as many others that Julia offers can be found in the documentation [here](https://docs.julialang.org/en/v1.7/base/collections/)

In [34]:
macro javascript_str(s) display("text/javascript", s); end
javascript"""
function hideElements(elements, start) {
for(var i = 0, length = elements.length; i < length;i++) {
    if(i >= start) {
        elements[i].style.display = "none";
    }
}
}
var prompt_elements = document.getElementsByClassName("prompt");
hideElements(prompt_elements, 0)
"""